//
//  PrivateMethods.h
//  Draw3D
//
//  Created by Johannes Brands on 04/03/2023.
//

/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 21, 2022 at 6:51:24 AM Pacific Standard Time
* Operating System: Version 15.2.1 (Build 19C63)
* Image Source: /System/Library/Frameworks/SceneKit.framework/SceneKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SceneKit/SceneKit.h>

@interface SCNGeometryElement (PrivateMethods)
- (long) indicesChannelCount;
- (BOOL) hasInterleavedIndicesChannels;
@end
